name: Rollback

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version to rollback to (example: v1.0.5)"
        required: true

jobs:
  rollback:
    runs-on: ubuntu-latest

    steps:
      - name: Rollback VPS
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}

          script: |
            cd /opt/laravel-docker

            sed -i "s/^APP_VERSION=.*/APP_VERSION=${{ github.event.inputs.version }}/" .env

            docker compose -f docker-compose.prod.yml pull

            docker compose -f docker-compose.prod.yml up -d

            docker compose -f docker-compose.prod.yml restart nginx

            echo "Rollback completed to ${{ github.event.inputs.version }}"